// Generated by gencpp from file move_printer/TubeDimRequest.msg
// DO NOT EDIT!


#ifndef MOVE_PRINTER_MESSAGE_TUBEDIMREQUEST_H
#define MOVE_PRINTER_MESSAGE_TUBEDIMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_printer
{
template <class ContainerAllocator>
struct TubeDimRequest_
{
  typedef TubeDimRequest_<ContainerAllocator> Type;

  TubeDimRequest_()
    : diameter(0.0)
    , height(0.0)  {
    }
  TubeDimRequest_(const ContainerAllocator& _alloc)
    : diameter(0.0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef double _diameter_type;
  _diameter_type diameter;

   typedef double _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::move_printer::TubeDimRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_printer::TubeDimRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TubeDimRequest_

typedef ::move_printer::TubeDimRequest_<std::allocator<void> > TubeDimRequest;

typedef boost::shared_ptr< ::move_printer::TubeDimRequest > TubeDimRequestPtr;
typedef boost::shared_ptr< ::move_printer::TubeDimRequest const> TubeDimRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_printer::TubeDimRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_printer::TubeDimRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace move_printer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/melodic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::move_printer::TubeDimRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_printer::TubeDimRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_printer::TubeDimRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_printer::TubeDimRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_printer::TubeDimRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_printer::TubeDimRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_printer::TubeDimRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b7413eb4258a4d489693c688fe84dde";
  }

  static const char* value(const ::move_printer::TubeDimRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b7413eb4258a4d4ULL;
  static const uint64_t static_value2 = 0x89693c688fe84ddeULL;
};

template<class ContainerAllocator>
struct DataType< ::move_printer::TubeDimRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_printer/TubeDimRequest";
  }

  static const char* value(const ::move_printer::TubeDimRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_printer::TubeDimRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 diameter\n\
float64 height\n\
";
  }

  static const char* value(const ::move_printer::TubeDimRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_printer::TubeDimRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.diameter);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TubeDimRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_printer::TubeDimRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_printer::TubeDimRequest_<ContainerAllocator>& v)
  {
    s << indent << "diameter: ";
    Printer<double>::stream(s, indent + "  ", v.diameter);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_PRINTER_MESSAGE_TUBEDIMREQUEST_H
