// Generated by gencpp from file move_printer/TubeDimResponse.msg
// DO NOT EDIT!


#ifndef MOVE_PRINTER_MESSAGE_TUBEDIMRESPONSE_H
#define MOVE_PRINTER_MESSAGE_TUBEDIMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_printer
{
template <class ContainerAllocator>
struct TubeDimResponse_
{
  typedef TubeDimResponse_<ContainerAllocator> Type;

  TubeDimResponse_()
    : finished(false)  {
    }
  TubeDimResponse_(const ContainerAllocator& _alloc)
    : finished(false)  {
  (void)_alloc;
    }



   typedef uint8_t _finished_type;
  _finished_type finished;





  typedef boost::shared_ptr< ::move_printer::TubeDimResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_printer::TubeDimResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TubeDimResponse_

typedef ::move_printer::TubeDimResponse_<std::allocator<void> > TubeDimResponse;

typedef boost::shared_ptr< ::move_printer::TubeDimResponse > TubeDimResponsePtr;
typedef boost::shared_ptr< ::move_printer::TubeDimResponse const> TubeDimResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_printer::TubeDimResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_printer::TubeDimResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace move_printer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/melodic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::move_printer::TubeDimResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_printer::TubeDimResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_printer::TubeDimResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_printer::TubeDimResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_printer::TubeDimResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_printer::TubeDimResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_printer::TubeDimResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2797c797e620a950ba704492d72873b";
  }

  static const char* value(const ::move_printer::TubeDimResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2797c797e620a95ULL;
  static const uint64_t static_value2 = 0x0ba704492d72873bULL;
};

template<class ContainerAllocator>
struct DataType< ::move_printer::TubeDimResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_printer/TubeDimResponse";
  }

  static const char* value(const ::move_printer::TubeDimResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_printer::TubeDimResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool finished\n\
";
  }

  static const char* value(const ::move_printer::TubeDimResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_printer::TubeDimResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finished);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TubeDimResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_printer::TubeDimResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_printer::TubeDimResponse_<ContainerAllocator>& v)
  {
    s << indent << "finished: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finished);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_PRINTER_MESSAGE_TUBEDIMRESPONSE_H
