// Generated by gencpp from file move_printer/TubeDim.msg
// DO NOT EDIT!


#ifndef MOVE_PRINTER_MESSAGE_TUBEDIM_H
#define MOVE_PRINTER_MESSAGE_TUBEDIM_H

#include <ros/service_traits.h>


#include <move_printer/TubeDimRequest.h>
#include <move_printer/TubeDimResponse.h>


namespace move_printer
{

struct TubeDim
{

typedef TubeDimRequest Request;
typedef TubeDimResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TubeDim
} // namespace move_printer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_printer::TubeDim > {
  static const char* value()
  {
    return "c678a14ef9d5b45fe26fb9bff2534273";
  }

  static const char* value(const ::move_printer::TubeDim&) { return value(); }
};

template<>
struct DataType< ::move_printer::TubeDim > {
  static const char* value()
  {
    return "move_printer/TubeDim";
  }

  static const char* value(const ::move_printer::TubeDim&) { return value(); }
};


// service_traits::MD5Sum< ::move_printer::TubeDimRequest> should match 
// service_traits::MD5Sum< ::move_printer::TubeDim > 
template<>
struct MD5Sum< ::move_printer::TubeDimRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_printer::TubeDim >::value();
  }
  static const char* value(const ::move_printer::TubeDimRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_printer::TubeDimRequest> should match 
// service_traits::DataType< ::move_printer::TubeDim > 
template<>
struct DataType< ::move_printer::TubeDimRequest>
{
  static const char* value()
  {
    return DataType< ::move_printer::TubeDim >::value();
  }
  static const char* value(const ::move_printer::TubeDimRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_printer::TubeDimResponse> should match 
// service_traits::MD5Sum< ::move_printer::TubeDim > 
template<>
struct MD5Sum< ::move_printer::TubeDimResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_printer::TubeDim >::value();
  }
  static const char* value(const ::move_printer::TubeDimResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_printer::TubeDimResponse> should match 
// service_traits::DataType< ::move_printer::TubeDim > 
template<>
struct DataType< ::move_printer::TubeDimResponse>
{
  static const char* value()
  {
    return DataType< ::move_printer::TubeDim >::value();
  }
  static const char* value(const ::move_printer::TubeDimResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_PRINTER_MESSAGE_TUBEDIM_H
